### ISSUE TITLE
No references found

### ISSUE THREAD

**Issue by gamer-cndg** [gayanhewa/vscode-find-all-references#11]
After installing the extension on the latest Visual Studio Code 1.19.0, the extension fails to find any references. I have already reloaded, uninstalled and reinstalled the plugin, with the same result. I am testing this on some C++ code.

See the attached screenshots.
![screenshot from 2017-12-18 17-38-30](https://user-images.githubusercontent.com/6953776/34117084-d99ff47c-e41a-11e7-859e-bc5017099958.png)
![screenshot from 2017-12-18 17-39-01](https://user-images.githubusercontent.com/6953776/34117085-d9bc9370-e41a-11e7-8928-1f84f2472939.png)

**Comment by gamer-cndg** [comment]
Sorry, I failed to read the install the pre-requisites. A warning from the plugin would have been nice.

**Comment by gr-rahimi** [comment]
I have the same problem.

**Comment by arturo-salinas** [comment]
I have similar problem. The problem appears when I add a existent project to a workspace. The extension now just find references in one project.

**Comment by jcluo** [comment]
I think it is because the regex prefix added for cpp ^((?!").)* is not valid syntax for rg.

**Comment by hyperh** [comment]
+1 same issue

**Comment by eagi223** [comment]
Same issue for me as well. Running `rg <function name>` returns results, but using find all references gives me "No results". It was working fine for months, so I don't know what happened.
