### ISSUE TITLE
how to use find.all.references.options

### ISSUE THREAD

**Issue by chiuan** [gayanhewa/vscode-find-all-references#2]
thanks for this plugin!
and how to use find.all.references.options ?
can you show some example ? 
thanks so much!

**Comment by gayanhewa** [comment]
@chiuan version 0.1.3 had a small issue supporting additional options for ripgrep ( or any other engine). The latest release 0.2.0 allows you to add as many available options ( that applies to your search criteria )

ie. `    "find.all.references.options": "--max-count 1 --threads 5" `

This would result in the search limiting to return only 1 match per file and use 5 parallel threads to search the text making it pretty fast.

All available options for any engine can be found by running `rg --help` or you can find the man page online https://www.mankier.com/1/rg
